// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: services/v1/api.proto

package services

import (
	v1 "github.com/jetexe/pbuf-example/internal/pkg/grpc/messages/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDirectMessagesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Direct []*v1.Direct `protobuf:"bytes,1,rep,name=direct,proto3" json:"direct,omitempty"`
}

func (x *GetDirectMessagesResponse) Reset() {
	*x = GetDirectMessagesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDirectMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirectMessagesResponse) ProtoMessage() {}

func (x *GetDirectMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirectMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetDirectMessagesResponse) Descriptor() ([]byte, []int) {
	return file_services_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *GetDirectMessagesResponse) GetDirect() []*v1.Direct {
	if x != nil {
		return x.Direct
	}
	return nil
}

type GetDirectMessagesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
}

func (x *GetDirectMessagesRequest) Reset() {
	*x = GetDirectMessagesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDirectMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirectMessagesRequest) ProtoMessage() {}

func (x *GetDirectMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirectMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetDirectMessagesRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetDirectMessagesRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

type SendDirectMessagesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendDirectMessagesResponse) Reset() {
	*x = SendDirectMessagesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendDirectMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDirectMessagesResponse) ProtoMessage() {}

func (x *SendDirectMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDirectMessagesResponse.ProtoReflect.Descriptor instead.
func (*SendDirectMessagesResponse) Descriptor() ([]byte, []int) {
	return file_services_v1_api_proto_rawDescGZIP(), []int{2}
}

type SendDirectMessagesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message *v1.Direct `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SendDirectMessagesRequest) Reset() {
	*x = SendDirectMessagesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendDirectMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDirectMessagesRequest) ProtoMessage() {}

func (x *SendDirectMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDirectMessagesRequest.ProtoReflect.Descriptor instead.
func (*SendDirectMessagesRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_api_proto_rawDescGZIP(), []int{3}
}

func (x *SendDirectMessagesRequest) GetMessage() *v1.Direct {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_services_v1_api_proto protoreflect.FileDescriptor

var file_services_v1_api_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x70,
	0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2e, 0x76, 0x31, 0x1a, 0x19, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x76,
	0x31, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x48, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x06,
	0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x52, 0x06, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x22, 0x34, 0x0a, 0x18, 0x47, 0x65, 0x74,
	0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22,
	0x1c, 0x0a, 0x1a, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4a, 0x0a,
	0x19, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xe3, 0x01, 0x0a, 0x12, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x41, 0x50, 0x49, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x64, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x25, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x67, 0x0a, 0x12, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x26, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x44,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x47, 0x5a, 0x45, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x65,
	0x74, 0x65, 0x78, 0x65, 0x2f, 0x70, 0x62, 0x75, 0x66, 0x2d, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x3b,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_v1_api_proto_rawDescOnce sync.Once
	file_services_v1_api_proto_rawDescData = file_services_v1_api_proto_rawDesc
)

func file_services_v1_api_proto_rawDescGZIP() []byte {
	file_services_v1_api_proto_rawDescOnce.Do(func() {
		file_services_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_v1_api_proto_rawDescData)
	})
	return file_services_v1_api_proto_rawDescData
}

var file_services_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_services_v1_api_proto_goTypes = []interface{}{
	(*GetDirectMessagesResponse)(nil),  // 0: services.v1.GetDirectMessagesResponse
	(*GetDirectMessagesRequest)(nil),   // 1: services.v1.GetDirectMessagesRequest
	(*SendDirectMessagesResponse)(nil), // 2: services.v1.SendDirectMessagesResponse
	(*SendDirectMessagesRequest)(nil),  // 3: services.v1.SendDirectMessagesRequest
	(*v1.Direct)(nil),                  // 4: messages.v1.Direct
}
var file_services_v1_api_proto_depIdxs = []int32{
	4, // 0: services.v1.GetDirectMessagesResponse.direct:type_name -> messages.v1.Direct
	4, // 1: services.v1.SendDirectMessagesRequest.message:type_name -> messages.v1.Direct
	1, // 2: services.v1.MessagesAPIService.GetDirectMessages:input_type -> services.v1.GetDirectMessagesRequest
	3, // 3: services.v1.MessagesAPIService.SendDirectMessages:input_type -> services.v1.SendDirectMessagesRequest
	0, // 4: services.v1.MessagesAPIService.GetDirectMessages:output_type -> services.v1.GetDirectMessagesResponse
	2, // 5: services.v1.MessagesAPIService.SendDirectMessages:output_type -> services.v1.SendDirectMessagesResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_services_v1_api_proto_init() }
func file_services_v1_api_proto_init() {
	if File_services_v1_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_v1_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDirectMessagesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_v1_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDirectMessagesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_v1_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendDirectMessagesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_v1_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendDirectMessagesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_v1_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_v1_api_proto_goTypes,
		DependencyIndexes: file_services_v1_api_proto_depIdxs,
		MessageInfos:      file_services_v1_api_proto_msgTypes,
	}.Build()
	File_services_v1_api_proto = out.File
	file_services_v1_api_proto_rawDesc = nil
	file_services_v1_api_proto_goTypes = nil
	file_services_v1_api_proto_depIdxs = nil
}
